# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Daniel Kessler
description:      "This is a website"
url:              "http://dkess.me"
baseurl:          /

author:
  name:           'Daniel Kessler'
  url:            http://dkess.me

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
